// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://gowjkqhevhfckfaqnhkb.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvd2prcWhldmhmY2tmYXFuaGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxMDY2NDcsImV4cCI6MjA4MTY4MjY0N30.aial9tx3Qo3qYYz8G3wftHjaLgESlDC2BbpGEodEiOc';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});